services:
  - type: web
    name: chinese-chess-online
    runtime: node
    plan: free
    rootDir: online-server
    buildCommand: ""
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
